### ISSUE TITLE
右键未选中的笔记会导致程序崩溃

### ISSUE THREAD

**Issue by wenLiangcan** [WizTeam/WizQTClient#341]
在没有左键单击选中的情况下右键点击某个笔记会导致程序崩溃。
终端下的相关输出：

```
[DEBUG] try to set enterprise server ip :  "http://api.wiz.cn/"
[DEBUG] set server ip :  "http://api.wiz.cn/"
[DEBUG] set user id for token ;  "xxx"
[WARNING]: QWidget::setLayout: Attempting to set QLayout "" on QMainWindow "", which already has a layout ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (-5) ((null):0, (null))
[INFO] Start Login
[INFO] Login: token=xxx
[1]    2027 segmentation fault (core dumped)  WizNote
```

崩溃之后启动程序会出现下面的错误，需要再启动一次才能打开程序

```
"QLocalSocket::connectToServer: Connection refused"
```

**Comment by WizLxn** [comment]
详细的操作过程是什么？ 现在在笔记列表上点击右键，会选中鼠标所做笔记

**Comment by wenLiangcan** [comment]
第一种情况是，在完全没有笔记被选中时，直接右键一个笔记，这时候没有问题。     

第二种情况是，当有一个已经通过左键选中的笔记，尝试直接右键一个未被选中的笔记时，程序就崩溃了。     

![b](https://cloud.githubusercontent.com/assets/1244181/10159568/9e8dc82e-66cb-11e5-8f44-0a4a09beba32.gif)

**Comment by Carlos-Cai** [comment]
在arch也能重现这个bug，另外把一篇文章置顶或取消置顶，也会出现这样的现象，命令行里有提示说“Segmentation fault (core dumped)”。
我WizNote版本是arch源里的2.2.5.20150924-1，WizNote GUI上显示的版本是2.2.6 （2015.10.8 12：58），两个版本号不一致，这又是另外一个问题了。

**Comment by wenLiangcan** [comment]
@Carlos-Cai 我用的也是 Arch

**Comment by carloscai** [comment]
@CarlosCai 不知道解决的怎么样了。

**Comment by carloscai** [comment]
今天贴一下dmesg列出的信息，请 @WizLxn 告知还要提供什么信息，例如core文件？
```
$ dmesg | grep WizNote
[92266.789732] WizNote[2944]: segfault at 8 ip 00007f18202fea16 sp 00007fffaa63b350 error 4 in libQt5Widgets.so.5.5.1
[7f182018a000+67a000] 
```

**Comment by WizLxn** [comment]
抱歉迟复，前段时间在修改Mac上的问题。下周会对Linux上的bug进行修复。预计在下个版本中解决。

**Comment by WizLxn** [comment]
@carloscai  之前一直在Ubuntu上面测试，没有出现类似的问题，稍后会在Arch上检查一下。如果方便的话请提供一份core文件。

**Comment by WizLxn** [comment]
@wenLiangcan @carloscai   在Arch x64上面通过pacman安装WizNote，测试没有发现选中或者改变置顶的时候崩溃。
使用的操作系统类型和版本号是什么？最好可以提供一下core文件。

**Comment by wenLiangcan** [comment]
我的系统也是 Arch Linux x64，当前内核版本是 4.2.4-1-ARCH（跟我提这个 issue 时已不同）。

请问 core 文件是指 https://wiki.archlinux.org/index.php/Core_dump 说的么？      

然后根据上面所说在 `var/lib/systemd/coredump` 下的确有 `core.WizNote.xxx` 这样的文件，可是根据[这里](http://www.cyberciti.biz/tips/linux-core-dumps.html)所说，我用 `gdb /bin/WizNote ./core.WizNote.xxx` 却提示 `core.WizNote.xxx is not a core dump: File format not recognized` 所以不敢确定，如果是的话我发上来。     

另外，根据[这里](https://wiki.archlinux.org/index.php/Core_dump#Examining_a_core_dump)，我试了一下这些命令：
```shell
$ coredumpctl list
TIME                            PID   UID   GID SIG PRESENT EXE
Thu 2015-10-29 16:09:07 HKT   28270  1002  1004  11 * /usr/bin/WizNote
Thu 2015-10-29 16:15:13 HKT   31689  1002  1004  11 * /usr/bin/WizNote

$ coredumpctl info /usr/bin/WizNote
           PID: 28270 (WizNote)
           UID: 1002 (xxx)
           GID: 1004 (xxx)
        Signal: 11 (SEGV)
     Timestamp: Thu 2015-10-29 16:09:06 HKT (12min ago)
  Command Line: /usr/bin/WizNote
    Executable: /usr/bin/WizNote
 Control Group: /user.slice/user-1002.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1002.slice
       Session: c1
     Owner UID: 1002 (xxx)
           PID: 28270 (WizNote)
           UID: 1002 (xxx)
           GID: 1004 (xxx)
        Signal: 11 (SEGV)
     Timestamp: Thu 2015-10-29 16:09:06 HKT (12min ago)
  Command Line: /usr/bin/WizNote
    Executable: /usr/bin/WizNote
 Control Group: /user.slice/user-1002.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1002.slice
       Session: c1
     Owner UID: 1002 (xxx)
       Boot ID: 7d89c8eda96c439fb9fd7a4c96608cdf
    Machine ID: 13f73be37be24b4e9fb4066fc8ef32b1
      Hostname: ArchLinux
      Coredump: /var/lib/systemd/coredump/core.WizNote.1002.7d89c8eda96c439fb9fd7a4c9660
       Message: Process 28270 (WizNote) of user 1002 dumped core.

           PID: 31689 (WizNote)
           UID: 1002 (xxx)
           GID: 1004 (xxx)
        Signal: 11 (SEGV)
     Timestamp: Thu 2015-10-29 16:15:13 HKT (6min ago)
  Command Line: /usr/bin/WizNote
    Executable: /usr/bin/WizNote
 Control Group: /user.slice/user-1002.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1002.slice
       Session: c1
     Owner UID: 1002 (xxx)
       Boot ID: 7d89c8eda96c439fb9fd7a4c96608cdf
    Machine ID: 13f73be37be24b4e9fb4066fc8ef32b1
      Hostname: ArchLinux
      Coredump: /var/lib/systemd/coredump/core.WizNote.1002.7d89c8eda96c439fb9fd7a4c9660
       Message: Process 31689 (WizNote) of user 1002 dumped core.

$ coredumpctl gdb /usr/bin/WizNote 
           PID: 31689 (WizNote)
           UID: 1002 (xxx)
           GID: 1004 (xxx)
        Signal: 11 (SEGV)
     Timestamp: Thu 2015-10-29 16:15:13 HKT (7min ago)
  Command Line: /usr/bin/WizNote
    Executable: /usr/bin/WizNote
 Control Group: /user.slice/user-1002.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1002.slice
       Session: c1
     Owner UID: 1002 (xxx)
       Boot ID: 7d89c8eda96c439fb9fd7a4c96608cdf
    Machine ID: 13f73be37be24b4e9fb4066fc8ef32b1
      Hostname: ArchLinux
      Coredump: /var/lib/systemd/coredump/core.WizNote.1002.7d89c8eda96c439fb9fd7a4c96608cdf.31689.1446106513000000.lz4
       Message: Process 31689 (WizNote) of user 1002 dumped core.

GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/WizNote...(no debugging symbols found)...done.
[New LWP 31689]
[New LWP 31694]
[New LWP 31693]
[New LWP 31696]
[New LWP 31695]
[New LWP 31699]
[New LWP 31702]
[New LWP 32211]
[New LWP 31737]
[New LWP 31698]
[New LWP 32229]
[New LWP 31692]
[New LWP 31701]
[New LWP 31697]
[New LWP 31734]
[New LWP 31691]
[New LWP 31700]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/bin/WizNote'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5e6f878a16 in QAction::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
[Current thread is 1 (Thread 0x7f5e7447c7c0 (LWP 31689))]
```

**Comment by WizLxn** [comment]
#0  0x00007f5e6f878a16 in QAction::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
看输出有可能是某个地方产生了空指针。
可以把core文件发送到邮箱lxn@wiz.cn

**Comment by carloscai** [comment]
@WizLxn ，你好，我已经把coredump文件发到lxn@wiz.cn，请查收。若需协助可以回复邮件或在此留言。

**Comment by WizLxn** [comment]
@carloscai 系统默认生成的dz4文件是压缩过的，无法使用。解压后的core文件比较大，可以在本地查看把结果发到这里。
调试命令：
```
coredumpctl gdb WizNote
 
(gdb) bt
```
可以把堆栈信息粘贴到这里。

**Comment by carloscai** [comment]
我从列表中点选某篇文章、右键菜单选择置顶后程序crash
```
(gdb) bt
#0  0x00007fa56d75e400 in QAction::isChecked() const () from /usr/lib/libQt5Widgets.so.5
#1  0x00000000007134df in CWizDocumentListView::on_action_alwaysOnTop() ()
#2  0x00007fa56ca5f12a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#3  0x00007fa56d75d402 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#4  0x00007fa56d75f888 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007fa56d8e21b2 in ?? () from /usr/lib/libQt5Widgets.so.5
#6  0x00007fa56d8e847c in ?? () from /usr/lib/libQt5Widgets.so.5
#7  0x00007fa56d8ec380 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007fa56d7aa038 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007fa56d8ecdc3 in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#10 0x00007fa56d76701c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#11 0x00007fa56d76cbf9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007fa56ca309ab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#13 0x00007fa56d76bb02 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007fa56d7c48fd in ?? () from /usr/lib/libQt5Widgets.so.5
#15 0x00007fa56d7c6b5b in ?? () from /usr/lib/libQt5Widgets.so.5
#16 0x00007fa56d76701c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007fa56d76c4f6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007fa56ca309ab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#19 0x00007fa56cf90111 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#20 0x00007fa56cf91de5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#21 0x00007fa56cf77208 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/libQt5Gui.so.5
#22 0x00007fa55f0333c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#23 0x00007fa569e13dc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#24 0x00007fa569e14020 in ?? () from /usr/lib/libglib-2.0.so.0
#25 0x00007fa569e140cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#26 0x00007fa56ca8734f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#27 0x00007fa56ca2e37a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#28 0x00007fa56ca3633c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#29 0x0000000000679010 in mainCore(int, char**) ()
#30 0x000000000050582d in main ()
```

我在列表中点选某篇文章，右键弹出菜单，不管这个菜单再次左键选中这篇文章，第二次右键操作就会发生crash。
```
(gdb) bt
#0  0x00007fcc2e95ba16 in QAction::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
#1  0x0000000000713d8a in CWizDocumentListView::resetPermission() ()
#2  0x0000000000718425 in CWizDocumentListView::mousePressEvent(QMouseEvent*) ()
#3  0x00007fcc2e9a647f in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#4  0x00007fcc2eaa4e4e in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#5  0x00007fcc2ebca94b in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#6  0x00007fcc2dc2c79c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#7  0x00007fcc2e962ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007fcc2e968bf9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007fcc2dc2c9ab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#10 0x00007fcc2e967b02 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#11 0x00007fcc2e9c059b in ?? () from /usr/lib/libQt5Widgets.so.5
#12 0x00007fcc2e9c2b5b in ?? () from /usr/lib/libQt5Widgets.so.5
#13 0x00007fcc2e96301c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007fcc2e9684f6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007fcc2dc2c9ab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#16 0x00007fcc2e18c111 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#17 0x00007fcc2e18dde5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#18 0x00007fcc2e173208 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#19 0x00007fcc2022f3c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#20 0x00007fcc2b00fdc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#21 0x00007fcc2b010020 in ?? () from /usr/lib/libglib-2.0.so.0
#22 0x00007fcc2b0100cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#23 0x00007fcc2dc8334f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#24 0x00007fcc2dc2a37a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#25 0x00007fcc2dc3233c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#26 0x0000000000679010 in mainCore(int, char**) ()
#27 0x000000000050582d in main ()
```

**Comment by WizLxn** [comment]
看输出应该是在判断笔记置顶这个菜单项是否被选中的时候崩溃了。这个菜单项的对象是存在的。其他地方的右键菜单有没有问题，向编辑器或者笔记目录中的右键菜单。

**Comment by carloscai** [comment]
我这边的情况是，bug只发生在笔记列表那栏，笔记目录和编辑器这两栏怎么右键都不会发生。

**Comment by WizLxn** [comment]
可能的原因是重复添加action导致的，已经在2.3.1中修复。这周应该就可以更新。

**Comment by carloscai** [comment]
我更新到2.3.1后没有发生这个issue了。

**Comment by wenLiangcan** [comment]
嗯，更新到 2.3.1 后没有问题了
